name: coaching
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  data_persistence_repository:
    path: packages/data_persistence_repository
  firebase_core: ^2.11.0
  firestore_repository:
    path: packages/firestore_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  go_router: ^7.0.0
  intl: ^0.17.0
  responsive_builder: ^0.6.4

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
