name: coaching
description: Flutter project for coaching skills testing.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.2
  cloud_functions: ^4.3.4
  data_persistence_repository:
    path: packages/data_persistence_repository
  equatable: ^2.0.3
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_remote_config: ^4.2.3
  firestore_repository:
    path: packages/firestore_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  functions_repository:
    path: packages/functions_repository
  go_router: ^9.0.0
  intl: ^0.18.0
  js: ^0.6.7
  pdf: ^3.10.4
  responsive_builder: ^0.7.0
  storage_repository:
    path: packages/storage_repository
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
