// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0tPv9oHkh0pih4NinQJnW1MeSznCHgTg',
    appId: '1:975211132157:web:7f8a17682f6df6e96e3a94',
    messagingSenderId: '975211132157',
    projectId: 'coaching-test-3c129',
    authDomain: 'coaching-test-3c129.firebaseapp.com',
    storageBucket: 'coaching-test-3c129.appspot.com',
    measurementId: 'G-RX71XV0P46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCePhrwkk5AE-3ewBvuEyRsmi_4mphg_kA',
    appId: '1:975211132157:android:a86a158da9e49d446e3a94',
    messagingSenderId: '975211132157',
    projectId: 'coaching-test-3c129',
    storageBucket: 'coaching-test-3c129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxPeh3Gnp-7Z1sJqd9_2ZAihsFofa1yAc',
    appId: '1:975211132157:ios:612c589cc12312236e3a94',
    messagingSenderId: '975211132157',
    projectId: 'coaching-test-3c129',
    storageBucket: 'coaching-test-3c129.appspot.com',
    androidClientId: '975211132157-qpkdpi13ttv5v9r1a2pn1pvnpf2ilmvv.apps.googleusercontent.com',
    iosClientId: '975211132157-mpn2pihib0098vvjl2evanbcd9resa0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.coaching',
  );
}
